const upperBody = [
  { id: 0, part: '가슴', name: '덤벨 벤치 프레스' },
  { id: 1, part: '가슴', name: '체스트 프레스 머신' },
  { id: 2, part: '가슴', name: '펙덱 플라이' },
  { id: 3, part: '가슴', name: '벤치 프레스' },
  { id: 4, part: '가슴', name: '푸쉬업' },
  { id: 5, part: '가슴', name: '인클라인 푸쉬업' },
  { id: 6, part: '가슴', name: '어시스트 딥스' },
  { id: 7, part: '가슴', name: '밴드 체스트 프레스' },
  { id: 8, part: '가슴', name: '해머스트렝스 인클라인 체스트 프레스' },
  { id: 9, part: '가슴', name: '해머 벤치 프레스' },
  { id: 10, part: '등', name: '인버티드 로우' },
  { id: 11, part: '등', name: '하이 로우 머신' },
  { id: 12, part: '등', name: '라잉 백 익스텐션' },
  { id: 13, part: '등', name: '로프 암 풀 다운' },
  { id: 14, part: '등', name: '랫 풀다운 머신' },
  { id: 15, part: '등', name: '로우 로우 머신' },
  { id: 16, part: '등', name: '원 암 시티드 케이블 로우' },
  { id: 17, part: '등', name: '와이드 풀다운 머신' },
  { id: 18, part: '등', name: '랫 풀다운' },
  { id: 19, part: '등', name: '백 익스텐션' },
  { id: 20, part: '어깨', name: '숄더 프레스 머신' },
  { id: 21, part: '어깨', name: '오버헤드 프레스' },
  { id: 22, part: '어깨', name: '펙 덱 리어 델트' },
  { id: 23, part: '어깨', name: '벤트 오버 레터럴 레이즈' },
  { id: 24, part: '어깨', name: '리버스 케이블 플라이' },
  { id: 25, part: '어깨', name: '덤벨 숄더 프레스' },
  { id: 26, part: '어깨', name: '스미스 머신 오버헤드 프레스' },
  { id: 27, part: '어깨', name: '해머 스트렝스숄더 프레스' },
  { id: 28, part: '어깨', name: '시티드 오버헤드 프레스' },
  { id: 29, part: '어깨', name: '파이크 푸쉬업' },
  { id: 30, part: '삼두', name: '체어 딥스' },
  { id: 31, part: '삼두', name: '윌 푸쉬 업' },
  { id: 32, part: '삼두', name: '써클 암' },
  { id: 33, part: '삼두', name: '스탠딩 엘보우 클랩' },
  { id: 34, part: '삼두', name: '암 크로스오버' },
  { id: 35, part: '삼두', name: '닐링 트라이셉스 익스텐션' },
  { id: 36, part: '삼두', name: '스트레이트 암 덤벨 킥백' },
  { id: 37, part: '삼두', name: '숄더 익스터널 앤 인터널 로테이션' },
  { id: 38, part: '삼두', name: '프레이어 푸쉬' },
  { id: 39, part: '삼두', name: '인클라인 라잉 트라이셉 익스텐션' },
  { id: 40, part: '이두', name: '덤벨 바이셉 컬' },
  { id: 41, part: '이두', name: '덤벨 해머 컬' },
  { id: 42, part: '이두', name: '바벨 바이셉 컬' },
  { id: 43, part: '이두', name: '케이블 바이셉 컬' },
  { id: 44, part: '이두', name: '프리쳐 컬 머신' },
  { id: 45, part: '이두', name: '이지바 바이셉 컬' },
  { id: 46, part: '이두', name: '인클라인 덤벨 컬' },
  { id: 47, part: '이두', name: '케이블 해머 컬' },
  { id: 48, part: '이두', name: '덤벨 프리쳐 컬' },
  { id: 49, part: '이두', name: '암 컬 머신' },
  { id: 50, part: '전완근', name: '덤벨 리스트 컬' },
  { id: 51, part: '전완근', name: '바벨 리스트 컬' },
  { id: 52, part: '전완근', name: '리스트 롤러' },
  { id: 53, part: '전완근', name: '리버스 덤벨 리스트 컬' },
  { id: 54, part: '전완근', name: '리버스 바벨 리스트 컬' },
];

const upperPart = [
  { id: 0, part: '전체' },
  { id: 1, part: '가슴' },
  { id: 2, part: '등' },
  { id: 3, part: '어깨' },
  { id: 4, part: '삼두' },
  { id: 5, part: '이두' },
  { id: 6, part: '전완근' },
];

const lowerBody = [
  { id: 0, part: '다리', name: '레그 익스텐션' },
  { id: 1, part: '다리', name: '레그 컬' },
  { id: 2, part: '다리', name: '레그 프레스' },
  { id: 3, part: '다리', name: '스쿼트' },
  { id: 4, part: '다리', name: '바벨 스쿼트' },
  { id: 5, part: '다리', name: '스미스 머신 스쿼트' },
  { id: 6, part: '다리', name: '바벨 스티프 레그 데드리프트' },
  { id: 7, part: '다리', name: '사이드 런지' },
  { id: 8, part: '다리', name: '핵 스쿼트 머신' },
  { id: 9, part: '다리', name: '백 런지' },
  { id: 10, part: '엉덩이', name: '와이드 스쿼트' },
  { id: 11, part: '엉덩이', name: '힙 어브덕션 머신' },
  { id: 12, part: '엉덩이', name: '덤벨 런지' },
  { id: 13, part: '엉덩이', name: '런지' },
  { id: 14, part: '엉덩이', name: '워킹 런지' },
  { id: 15, part: '엉덩이', name: '힙 어브덕션' },
  { id: 16, part: '엉덩이', name: '사이드 킥 백' },
  { id: 17, part: '엉덩이', name: '덤벨 스티프 레그 데드리프트' },
  { id: 18, part: '엉덩이', name: '스미스 머신 런지' },
  { id: 19, part: '엉덩이', name: '원 레그 덤벨 데드리프트' },
];

export { upperBody, upperPart, lowerBody };
